export default {
  /********************* BottomTabs  Icons **********************/
  firstActiveIcon: require('../assets/images/ActiveHome.png'),
  firstInActiveIcon: require('../assets/images/InactiveHome.png'),
  secondActiveIcon: require('../assets/images/search.png'),
  secondInActiveIcon: require('../assets/images/search.png'),
  thirdActiveIcon: require('../assets/images/activeplus.png'),
  thirdInActiveIcon: require('../assets/images/inactiveplus.png'),
  fourthActiveIcon: require('../assets/images/activeNotification.png'),
  fourthInActiveIcon: require('../assets/images/inactiveNotification.png'),
  fifthActiveIcon: require('../assets/images/activeProfile.png'),
  fifthInActiveIcon: require('../assets/images/inactiveProfile.png'),

  /********************* App Icons **********************/
  icLogo: require('../assets/images/Logo.png'),
  icGoogle: require('../assets/images/google.png'),
  icFacebook: require('../assets/images/facebook.png'),
  icApple: require('../assets/images/apple.png'),
  icBack: require('../assets/images/ArrowLeft.png'),
  icCheck: require('../assets/images/check-circle.png'),
  icCheckFill: require('../assets/images/verifed.png'),
  icDots: require('../assets/images/dots.png'),
  icShare: require('../assets/images/right.png'),
  icEdit: require('../assets/images/edit.png'),
  icLink: require('../assets/images/link.png'),
  icRight_Arrow: require('../assets/images/right_arrow.png'),
  icAdd: require('../assets/images/add.png'),
  icCamera: require('../assets/images/camera.png'),
  icCross: require('../assets/images/remove.png'),
  icHeart: require('../assets/images/love.png'),
  icHeartFill: require('../assets/images/fillLove.png'),
};
